### ISSUE TITLE
Refinments editor won't open for an instrument with a distrotion function

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1021]
@psavery I just noticed this one working with the GE CeO2 example.  Looks related to the fact that the instrument has an additional 6 parameters hanging off it.

```
Traceback (most recent call last):
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\main_window.py", line 626, in edit_refinements
    w = self._refinements_editor = RefinementsEditor(self.ui)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\refinements_editor.py", line 20, in __init__
    self.reset_dict()
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\refinements_editor.py", line 46, in reset_dict
    config['materials'] = self.create_materials_dict()
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\refinements_editor.py", line 102, in create_materials_dict
    values = refinement_values(overlay)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\refinements_editor.py", line 266, in refinement_values
    return func_dict[overlay['type']]()
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\refinements_editor.py", line 244, in powder_values
    x = reduced_lparms[i]
IndexError: list index out of range
```

**Comment by psavery** [comment]
@joelvbernier This actually looks like there is something off with the number of overlay refinements. The distortion parameters are not actually involved in that function with the error, only the overlay refinements. (also, I am not getting an issue with the refinements editor when using the GE CeO2 config with distortion parameters).

Can you send me a screen shot of your CeO2 powder overlay settings, like this one?

![ceo2_refinements](https://user-images.githubusercontent.com/9558430/132366836-5a393081-f396-40a6-9699-06789f36fbb5.png)

There should only be one refinement.

Also, are you using the default CeO2 material?

**Comment by joelvbernier** [comment]
Currently, when you ask the instrument for its calibration parameters, if a distortion function is present, attacks them to the end of the six geometric parameters.  It would appear that the flags are not including these additional parameters.
