### ISSUE TITLE
Issues with Finger, Cox, Jephcoat profile function

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1026]
Seems like this profile function is prone to exceptions in the GUI implementation.

For example, I get the following `ZeroDivisionError`
```
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joel/Documents/GitHub/hexrdgui/hexrd/ui/calibration/wppf_runner.py", line 57, in run_wppf
    refine_func()
  File "/home/joel/Documents/GitHub/hexrd/hexrd/wppf/WPPF.py", line 605, in RefineCycle
    self.res = self.Refine()
  File "/home/joel/Documents/GitHub/hexrd/hexrd/wppf/WPPF.py", line 631, in Refine
    res = fitter.least_squares(**fdict)
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/lmfit/minimizer.py", line 1577, in least_squares
    ret = least_squares(self.__residual, start_vals,
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/scipy/optimize/_lsq/least_squares.py", line 928, in least_squares
    result = trf(fun_wrapped, jac_wrapped, x0, f0, J0, lb, ub, ftol, xtol,
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/scipy/optimize/_lsq/trf.py", line 123, in trf
    return trf_bounds(
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/scipy/optimize/_lsq/trf.py", line 338, in trf_bounds
    f_new = fun(x_new)
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/scipy/optimize/_lsq/least_squares.py", line 815, in fun_wrapped
    return np.atleast_1d(fun(x, *args, **kwargs))
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/lmfit/minimizer.py", line 590, in __residual
    out = self.userfcn(params, *self.userargs, **self.userkws)
  File "/home/joel/Documents/GitHub/hexrd/hexrd/wppf/WPPF.py", line 573, in calcRwp
    errvec = self.computespectrum()
  File "/home/joel/Documents/GitHub/hexrd/hexrd/wppf/WPPF.py", line 454, in computespectrum
    y += self.computespectrum_fcn(*args)
SystemError: PyEval_EvalFrameEx returned a result with an error set
```
for these parameters:
![image](https://user-images.githubusercontent.com/1154130/132586682-ad4a1763-9b7d-4dd0-a04e-50893511980c.png)

**Comment by joelvbernier** [comment]
@saransh13 can you take a look at this by the end of next week?

**Comment by saransh13** [comment]
You should only refine either `HL` or `SL`. Refining both of them simultaneously is leading to this. The least squares wanders off in bad territory. Can you try with just one of those parameters turned on.

**Comment by saransh13** [comment]
The angular range for the spectrum starts at 2 degrees. The values of `HL` and `SL` needed to be made small to get a good starting point for least squares. When either or both are `0`, that's when that divide by her error is raised. I'll fix the default values for the table and close this issue.
