### ISSUE TITLE
Fresh development build problems on Linux

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1049]
After setting up a fresh dev environment with the following:
```
conda create --name hexrdgui_dev python=3.8 hexrdgui -c hexrd/label/hexrd-prerelease -c hexrd/label/hexrdgui-prerelease -c hexrd -c conda-forge
conda activate hexrdgui_dev
CONDA_BUILD=1
pip install --no-build-isolation --no-deps -U -e hexrd
pip install --no-build-isolation --no-deps -U -e hexrdgui
```
the `hexrdgui` entry point no longer works:
```
Traceback (most recent call last):
  File "/home/joel/miniconda3/envs/hexrdgui_dev/bin/hexrdgui", line 33, in <module>
    sys.exit(load_entry_point('hexrdgui', 'gui_scripts', 'hexrdgui')())
  File "/home/joel/miniconda3/envs/hexrdgui_dev/bin/hexrdgui", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/joel/Documents/GitHub/hexrdgui/hexrd/ui/main.py", line 9, in <module>
    from hexrd.ui.main_window import MainWindow
  File "/home/joel/Documents/GitHub/hexrdgui/hexrd/ui/main_window.py", line 12, in <module>
    from hexrd.ui.async_runner import AsyncRunner
  File "/home/joel/Documents/GitHub/hexrdgui/hexrd/ui/async_runner.py", line 5, in <module>
    from hexrd.ui.progress_dialog import ProgressDialog
  File "/home/joel/Documents/GitHub/hexrdgui/hexrd/ui/progress_dialog.py", line 3, in <module>
    from hexrd.ui.messages_widget import MessagesWidget
  File "/home/joel/Documents/GitHub/hexrdgui/hexrd/ui/messages_widget.py", line 9, in <module>
    from hexrd.ui.hexrd_config import HexrdConfig
  File "/home/joel/Documents/GitHub/hexrdgui/hexrd/ui/hexrd_config.py", line 13, in <module>
    import hexrd.imageseries.save
  File "/home/joel/Documents/GitHub/hexrd/hexrd/imageseries/__init__.py", line 10, in <module>
    from . import save
  File "/home/joel/Documents/GitHub/hexrd/hexrd/imageseries/save.py", line 14, in <module>
    from hexrd.matrixutil import extract_ijv
  File "/home/joel/Documents/GitHub/hexrd/hexrd/matrixutil.py", line 35, in <module>
    from hexrd import constants
  File "/home/joel/Documents/GitHub/hexrd/hexrd/constants.py", line 134, in <module>
    import numba
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/numba/__init__.py", line 19, in <module>
    from numba.core import config
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/numba/core/config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/llvmlite/binding/dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/llvmlite/binding/ffi.py", line 175, in <module>
    from pkg_resources import resource_filename
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/joel/miniconda3/envs/hexrdgui_dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyside2' distribution was not found and is required by hexrdgui
```
I can call the `main.py` script to fire up the GUI directly, however.  Also note that a straight conda build env works as expected.

**Comment by joelvbernier** [comment]
D'oh -- as @psavery pointed out, I flubbed my shell var scoping rules trying to be cute.  My bad.  The _actual_ instructions work:
```
conda create --name hexrdgui_dev python=3.8 hexrdgui -c hexrd/label/hexrd-prerelease -c hexrd/label/hexrdgui-prerelease -c hexrd -c conda-forge
conda activate hexrdgui_dev
CONDA_BUILD=1 pip install --no-build-isolation --no-deps -U -e hexrd
CONDA_BUILD=1 pip install --no-build-isolation --no-deps -U -e hexrdgui
```
