### ISSUE TITLE
Failure upon subsequent save of instrument config to 'HEXRD' format on Windows

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1078]
If you attempt to save the instrument config to HEXRD (hdf5) format more than once in a GUI session, the following exception is raised:
```
Traceback (most recent call last):
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\main_window.py", line 320, in on_action_save_config_hexrd_triggered
    self._save_config('.hexrd', 'HEXRD files (*.hexrd)')
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\main_window.py", line 317, in _save_config
    return HexrdConfig().save_instrument_config(selected_file)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\hexrd_config.py", line 665, in save_instrument_config
    instr.write_config(output_file, style=styles[ext])
  File "c:\users\berni\documents\github\hexrd\hexrd\instrument.py", line 794, in write_config
    with h5py.File(file, 'w') as f:
  File "C:\Users\berni\miniconda3\envs\hexrdgui_dev\lib\site-packages\h5py\_hl\files.py", line 455, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "C:\Users\berni\miniconda3\envs\hexrdgui_dev\lib\site-packages\h5py\_hl\files.py", line 205, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 120, in h5py.h5f.create
OSError: [Errno 0] Unable to create file (unable to lock file, errno = 0, error message = 'No error', Win32 GetLastError() = 33)
```
Furthermore, the file that gets written is a garbage config with all fields are set to 0 (or False) despite the values stored in the instrument parameter dict on `HexrdConfig` in the GUi namespace, _e.g._:
```
{'Pilatus2M_0_0': {'buffer': array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]]), 'pixels': {'columns': 0, 'rows': 0, 'size': array([0., 0.])}, 'saturation_level': 0.0, 'transform': {'tilt': array([0., 0., 0.]), 'translation': array([0., 0., 0.])}}, 'Pilatus2M_0_1': {'buffer': array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]]), 'pixels': {'columns': 0, 'rows': 0, 'size': array([0., 0.])}, 'saturation_level': 0.0, 'transform': {'tilt': array([0., 0., 0.]), 'translation': array([0., 0., 0.])}}, 'Pilatus2M_0_2': {'buffer': array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]]), 'pixels': {'columns': 0, 'rows': 0, 'size': array([0., 0.])}, 'saturation_level': 0.0, 'transform': {'tilt': array([0., 0., 0.]), 'translation': array([0., 0., 0.])}}, 'Pilatus2M_1_0': {'buffer': array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]]), 'pixels': {'columns': 0, 'rows': 0, 'size': array([0., 0.])}, 'saturation_level': 0.0, 'transform': {'tilt': array([0., 0., 0.]), 'translation': array([0., 0., 0.])}}, ...
```
This is exclusive to the Windows implementation; not reproducible on Mac OS or Linux.

**Comment by joelvbernier** [comment]
Upon further examination, the _seems_ to be due to the fact that I had instantiated an instrument class from the same hdf5 file in an IPython session open at the same time.  Closing that removed the issue.  Not sure how on earth it wrote all those 0's in the example above, but take this as a cautionary tale opening the same hdf5 file in multiple processes on Windows!
