### ISSUE TITLE
Add/Remove detector buttons in form view not working on mac os

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1092]
Weird, new bug; the '+' and '-' buttons in the form view aren't doing anything on the mac version.  Here is my dev env off of master (note it is built using conda-forge's python 3.8.12 and not our 'special' python 3.8.4):
```
# packages in environment at /Users/joel/opt/miniconda3/envs/hexrdgui-dev:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.2            py38h50d1736_1    conda-forge
asteval                   0.9.23             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blosc                     1.21.0               he49afe7_0    conda-forge
brotli                    1.0.9                h0d85af4_5    conda-forge
brotli-bin                1.0.9                h0d85af4_5    conda-forge
brotlipy                  0.7.0           py38h96a0964_1001    conda-forge
brunsli                   0.1                  h046ec9c_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.17.2               h0d85af4_0    conda-forge
c-blosc2                  2.0.4                ha1a4663_1    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2021.10.8        py38h50d1736_0    conda-forge
cffi                      1.14.6           py38h1a44b6c_1    conda-forge
cfitsio                   4.0.0                hb20e66c_0    conda-forge
chardet                   4.0.0            py38h50d1736_1    conda-forge
charls                    2.2.0                h046ec9c_0    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
cryptography              35.0.0           py38hcc27614_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py38h96a0964_3    conda-forge
dask-core                 2021.9.1           pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               ha13b53f_2    conda-forge
debugpy                   1.4.1            py38ha048514_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.4.1                he49afe7_0    conda-forge
fabio                     0.12.0           py38hbe852b5_0    conda-forge
fast-histogram            0.10             py38hbe852b5_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fsspec                    2021.10.1          pyhd8ed1ab_0    conda-forge
future                    0.18.2           py38h50d1736_3    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glib                      2.70.0               hcf210ce_0    conda-forge
glib-tools                2.70.0               hcf210ce_0    conda-forge
glymur                    0.9.4              pyhd8ed1ab_0    conda-forge
h5py                      3.4.0           nompi_py38h9f21798_101    conda-forge
hdf4                      4.2.15               hefd3b78_3    conda-forge
hdf5                      1.12.1          nompi_h2f0ef1a_101    conda-forge
hexrd                     0.8.13.dev33+g1f0128b           dev_0    <develop>
hexrdgui                  0.8.11.dev28+g3dae960           dev_0    <develop>
icu                       68.1                 h74dc148_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
imagecodecs               2021.8.26        py38hdf6b4c7_2    conda-forge
imageio                   2.9.0                      py_0    conda-forge
importlib_resources       5.3.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.4.2            py38h5fd9f69_0    conda-forge
ipython                   7.28.0           py38h5fd9f69_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.0           py38h50d1736_2    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
jupyter_client            7.0.6              pyhd8ed1ab_0    conda-forge
jupyter_core              4.8.1            py38h50d1736_0    conda-forge
jxrlib                    1.1                  h35c211d_2    conda-forge
kiwisolver                1.3.2            py38h12bbefe_0    conda-forge
krb5                      1.19.2               hcfbf3a7_2    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libaec                    1.0.6                he49afe7_0    conda-forge
libblas                   3.9.0           12_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h0d85af4_5    conda-forge
libbrotlidec              1.0.9                h0d85af4_5    conda-forge
libbrotlienc              1.0.9                h0d85af4_5    conda-forge
libcblas                  3.9.0           12_osx64_openblas    conda-forge
libclang                  11.1.0          default_he082bbe_1    conda-forge
libcurl                   7.79.1               hf45b732_1    conda-forge
libcxx                    12.0.1               habf9029_0    conda-forge
libdeflate                1.8                  h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                he49afe7_4    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.0               hf1fb8c0_0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0           12_osx64_openblas    conda-forge
libllvm11                 11.1.0               hd011deb_2    conda-forge
libnghttp2                1.43.0               h6f36284_1    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     13.3                 hea3049e_1    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.3.0                hd146c10_2    conda-forge
libwebp-base              1.2.1                h0d85af4_0    conda-forge
libxml2                   2.9.12               h93ec3fd_0    conda-forge
libxslt                   1.1.33               h5739fc3_2    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
libzopfli                 1.0.3                h046ec9c_0    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
llvmlite                  0.37.0           py38h872f124_0    conda-forge
lmfit                     1.0.2              pyhd8ed1ab_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.6.3            py38h6ea4786_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
mako                      1.1.5              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py38h96a0964_0    conda-forge
matplotlib                3.4.3            py38h50d1736_1    conda-forge
matplotlib-base           3.4.3            py38hc7d2367_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mysql-common              8.0.26               h694c41f_0    conda-forge
mysql-libs                8.0.26               h115446f_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.3                        py_0    conda-forge
nspr                      4.30                 hcd9eead_0    conda-forge
nss                       3.69                 h31e2bf1_1    conda-forge
numba                     0.54.1           py38h41dd760_0    conda-forge
numpy                     1.20.3           py38had91d27_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   1.1.1l               h0d85af4_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.3.2            py38hee640a0_0    conda-forge
pip                       21.3               pyhd8ed1ab_0    conda-forge
pooch                     1.5.2              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.20             pyha770c72_0    conda-forge
psutil                    5.8.0            py38h96a0964_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycifrw                   4.4.1            py38h4d0b108_2    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyhdf                     0.10.3           py38he785675_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38h50d1736_7    conda-forge
pyqt-impl                 5.12.3           py38h721a93c_7    conda-forge
pyqt5-sip                 4.19.18          py38h5745d40_7    conda-forge
pyqtchart                 5.12             py38h721a93c_7    conda-forge
pyqtwebengine             5.12.1           py38h721a93c_7    conda-forge
pyside2                   5.13.2           py38hc6340e1_4    conda-forge
pysocks                   1.7.1            py38h50d1736_3    conda-forge
python                    3.8.12          h17280f6_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-xxhash             2.0.2            py38h96a0964_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pywavelets                1.1.1            py38hbe852b5_3    conda-forge
pyyaml                    6.0              py38h96a0964_0    conda-forge
pyzmq                     22.3.0           py38hd3b92b6_0    conda-forge
qt                        5.12.9               h126340a_4    conda-forge
qtconsole                 5.1.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.11.2             pyhd8ed1ab_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
scikit-image              0.18.3           py38ha53d530_0    conda-forge
scikit-learn              1.0              py38h1021539_1    conda-forge
scipy                     1.7.1            py38hd329d04_0    conda-forge
setuptools                58.2.0           py38h50d1736_0    conda-forge
silx                      0.15.2               hd8ed1ab_0    conda-forge
silx-base                 0.15.2           py38h1f261ad_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                hb1e8313_3    conda-forge
sqlite                    3.36.0               h23a322b_2    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tifffile                  2021.10.12         pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h5dbffcc_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h96a0964_1    conda-forge
traitlets                 5.1.0              pyhd8ed1ab_0    conda-forge
uncertainties             3.1.6              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xxhash                    0.8.0                h35c211d_3    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zfp                       0.5.5                h4a89273_7    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.0                h582d3a0_0    conda-forge
```

**Comment by joelvbernier** [comment]
Ok -- to produce this, I did the following:

1. I had a session with a rotation series overlay selected for the [single GE instrument](https://github.com/HEXRD/examples/blob/master/NIST_ruby/single_GE/include/ge_detector.yml).
2. I had also loaded a GE imageseries and max aggregated it
3. I loaded into this session the reference tardis config, which produced the following exception:
```Traceback (most recent call last):
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_canvas.py", line 418, in update_overlays
    self.iviewer.update_overlay_data()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/calibration/raw_iviewer.py", line 18, in update_overlay_data
    update_overlay_data(self.instr, self.type)
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/overlays/__init__.py", line 115, in update_overlay_data
    overlay['data'] = generator.overlay(display_mode)
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/overlays/rotation_series.py", line 126, in overlay
    sim_data = self.instrument.simulate_rotation_series(
  File "/Users/joel/Documents/GitHub/hexrd/hexrd/instrument.py", line 1413, in simulate_rotation_series
    results[det_key] = panel.simulate_rotation_series(
  File "/Users/joel/Documents/GitHub/hexrd/hexrd/instrument.py", line 3067, in simulate_rotation_series
    full_hkls = xrdutil._fetch_hkls_from_planedata(plane_data)
  File "/Users/joel/Documents/GitHub/hexrd/hexrd/xrdutil/utils.py", line 1047, in _fetch_hkls_from_planedata
    return np.hstack(pd.getSymHKLs(withID=True)).T
  File "<__array_function__ internals>", line 5, in hstack
  File "/Users/joel/opt/miniconda3/envs/hexrdgui-dev/lib/python3.8/site-packages/numpy/core/shape_base.py", line 346, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
Traceback (most recent call last):
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/main_window.py", line 342, in on_detectors_changed
    self.load_dummy_images()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/main_window.py", line 352, in load_dummy_images
    self.update_all(clear_canvases=True)
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/main_window.py", line 778, in update_all
    self.ui.image_tab_widget.load_images()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_tab_widget.py", line 119, in load_images
    self.load_images_untabbed()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_tab_widget.py", line 99, in load_images_untabbed
    self.image_canvases[0].load_images(
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_canvas.py", line 173, in load_images
    self.update_overlays()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_canvas.py", line 418, in update_overlays
    self.iviewer.update_overlay_data()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/calibration/raw_iviewer.py", line 18, in update_overlay_data
    update_overlay_data(self.instr, self.type)
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/overlays/__init__.py", line 115, in update_overlay_data
    overlay['data'] = generator.overlay(display_mode)
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/overlays/rotation_series.py", line 126, in overlay
    sim_data = self.instrument.simulate_rotation_series(
  File "/Users/joel/Documents/GitHub/hexrd/hexrd/instrument.py", line 1413, in simulate_rotation_series
    results[det_key] = panel.simulate_rotation_series(
  File "/Users/joel/Documents/GitHub/hexrd/hexrd/instrument.py", line 3067, in simulate_rotation_series
    full_hkls = xrdutil._fetch_hkls_from_planedata(plane_data)
  File "/Users/joel/Documents/GitHub/hexrd/hexrd/xrdutil/utils.py", line 1047, in _fetch_hkls_from_planedata
    return np.hstack(pd.getSymHKLs(withID=True)).T
  File "<__array_function__ internals>", line 5, in hstack
  File "/Users/joel/opt/miniconda3/envs/hexrdgui-dev/lib/python3.8/site-packages/numpy/core/shape_base.py", line 346, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
```
4. while the Tardis appeared to load, the '+' and '-' buttons (at least) had no effect.  I had to quit and restart the GUI to clear things up.

**Comment by psavery** [comment]
Hmm. I'm able to reproduce this on Linux. It is very odd. I guess that exception is putting some parts of the program in an invalid state. It looks like after that exception occurs, the button's connected function isn't being called at all. I don't know how/why the button would get disconnected.

Maybe we can try to prevent the exception? I can call `plane_data.getHKLs()` before trying to call `simulate_rotation_series()` to double-check and make sure there are some hkls returned.

We could also try to prevent the exception in `simulate_rotation_series()`. For instance, add a check in `_fetch_hkls_from_planedata()`:
```python
def _fetch_hkls_from_planedata(pd):
    hkls = pd.getSymHKLs(withID=True)
    if len(hkls) == 0:
        return np.array([])

    return np.hstack(hkls).T
```

Plus a check in `simulate_rotation_series()`:
```python
if len(full_hkls) == 0:
    # all empty lists
    return valid_ids, valid_hkls, valid_angs, valid_xys, ang_pixel_size
```

**Comment by psavery** [comment]
@saransh13 Do you think this is still an issue?

**Comment by psavery** [comment]
I think this has been working for a while. We used it recently 🙂
