### ISSUE TITLE
Issue Saving Triclinic Material In GUI

### ISSUE THREAD

**Issue by darrencpagan** [HEXRD/hexrdgui#1094]
Tried saving the material below

![matl](https://user-images.githubusercontent.com/7535678/143782944-db8e9079-1479-43af-a795-91a0c49650e0.png)

and got the error stack:
```
Traceback (most recent call last):
  File "/tri-s-1/s2/dcp5303/sw/miniconda3/envs/20211123_hexrdgui/lib/python3.8/site-packages/hexrd/ui/main_window.py", line 448, in on_action_save_materials_triggered
    return HexrdConfig().save_materials(selected_file)
  File "/tri-s-1/s2/dcp5303/sw/miniconda3/envs/20211123_hexrdgui/lib/python3.8/site-packages/hexrd/ui/hexrd_config.py", line 688, in save_materials
    save_materials_hdf5(f, self.materials, path)
  File "/tri-s-1/s2/dcp5303/sw/miniconda3/envs/20211123_hexrdgui/lib/python3.8/site-packages/hexrd/material.py", line 1120, in save_materials_hdf5
    material.dump_material(f, path)
  File "/tri-s-1/s2/dcp5303/sw/miniconda3/envs/20211123_hexrdgui/lib/python3.8/site-packages/hexrd/material.py", line 711, in dump_material
    Write2H5File(AtomInfo, lat_param, path)
  File "/tri-s-1/s2/dcp5303/sw/miniconda3/envs/20211123_hexrdgui/lib/python3.8/site-packages/hexrd/mksupport.py", line 470, in Write2H5File
    WriteH5Data(fid, AtomInfo, lat_param, path)
  File "/tri-s-1/s2/dcp5303/sw/miniconda3/envs/20211123_hexrdgui/lib/python3.8/site-packages/hexrd/mksupport.py", line 521, in WriteH5Data
    did.write_direct(AtomInfo['hkls'])
  File "/tri-s-1/s2/dcp5303/sw/miniconda3/envs/20211123_hexrdgui/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 990, in write_direct
    for fspace in dest_sel.broadcast(source_sel.array_shape):
  File "/tri-s-1/s2/dcp5303/sw/miniconda3/envs/20211123_hexrdgui/lib/python3.8/site-packages/h5py/_hl/selections.py", line 293, in broadcast
    chunks = tuple(x//y for x, y in zip(count, tshape))
  File "/tri-s-1/s2/dcp5303/sw/miniconda3/envs/20211123_hexrdgui/lib/python3.8/site-packages/h5py/_hl/selections.py", line 293, in <genexpr>
    chunks = tuple(x//y for x, y in zip(count, tshape))
ZeroDivisionError: integer division or modulo by zero
```

**Comment by psavery** [comment]
Looks like this is something that needs to be fixed in `mksupport` @saransh13?

**Comment by saransh13** [comment]
Looks like there are no reflection to save and that's why it's raising the error. The same set of lattice parameter gives me 3 reflections, so I don't know why there are no reflections in this case. I can do a check before writing, which should fix this particular issue.

**Comment by saransh13** [comment]
Fixed in master.

**Comment by joelvbernier** [comment]
Fixed in master (a while ago)
