### ISSUE TITLE
Materials and state save is broken

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1154]
In the current release, state and materials saving is broken.  Looks like it is probably related to https://github.com/HEXRD/hexrd/pull/394, but I need to verify.  Observe:
```
Traceback (most recent call last):
  File "/Users/joel/opt/miniconda3/envs/hexrdgui-release/lib/python3.9/site-packages/hexrd/ui/main_window.py", line 453, in on_action_save_materials_triggered
    return HexrdConfig().save_materials(selected_file)
  File "/Users/joel/opt/miniconda3/envs/hexrdgui-release/lib/python3.9/site-packages/hexrd/ui/hexrd_config.py", line 714, in save_materials
    save_materials_hdf5(f, self.materials, path)
  File "/Users/joel/opt/miniconda3/envs/hexrdgui-release/lib/python3.9/site-packages/hexrd/material.py", line 1171, in save_materials_hdf5
    material.dump_material(f, path)
  File "/Users/joel/opt/miniconda3/envs/hexrdgui-release/lib/python3.9/site-packages/hexrd/material.py", line 758, in dump_material
    Write2H5File(AtomInfo, lat_param, path)
  File "/Users/joel/opt/miniconda3/envs/hexrdgui-release/lib/python3.9/site-packages/hexrd/mksupport.py", line 470, in Write2H5File
    WriteH5Data(fid, AtomInfo, lat_param, path)
  File "/Users/joel/opt/miniconda3/envs/hexrdgui-release/lib/python3.9/site-packages/hexrd/mksupport.py", line 527, in WriteH5Data
    did.write_direct(AtomInfo['hkls'])
  File "/Users/joel/opt/miniconda3/envs/hexrdgui-release/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 1000, in write_direct
    for fspace in dest_sel.broadcast(source_sel.array_shape):
  File "/Users/joel/opt/miniconda3/envs/hexrdgui-release/lib/python3.9/site-packages/h5py/_hl/selections.py", line 293, in broadcast
    chunks = tuple(x//y for x, y in zip(count, tshape))
  File "/Users/joel/opt/miniconda3/envs/hexrdgui-release/lib/python3.9/site-packages/h5py/_hl/selections.py", line 293, in <genexpr>
    chunks = tuple(x//y for x, y in zip(count, tshape))
ZeroDivisionError: integer division or modulo by zero
```
Can you track this down @saransh13?

**Comment by psavery** [comment]
I gave this a try, and I can reproduce this if I try to save the materials/state when there is a material where no hkls are selected. I guess this would mean the `AtomInfo['hkls']` would be empty, and this caused an error in h5py.

**Comment by saransh13** [comment]
Fixed in PR https://github.com/HEXRD/hexrd/pull/400
