### ISSUE TITLE
Rolling back to 0.8.15

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1157]
There are a few issues in the overlays right now, so I was rolling back to the last stable release. Getting the following error when I launch the GUI

```"QFormBuilder was unable to create a custom widget of the class 'ImageTabWidget'; defaulting to base class 'QTabWidget'."
"Empty widget item in QVBoxLayout 'central_widget_layout'."
Designer: The creation of a widget of the class '' failed.
Designer: The creation of a widget of the class '' failed.
Designer: The creation of a widget of the class '' failed.
Designer: The creation of a widget of the class '' failed.
Designer: The creation of a widget of the class '' failed.
Designer: The creation of a widget of the class '' failed.
Traceback (most recent call last):
  File "/Users/saransh1/opt/miniconda3/envs/hexrd/bin/hexrdgui", line 33, in <module>
    sys.exit(load_entry_point('hexrdgui', 'gui_scripts', 'hexrdgui')())
  File "/Users/saransh1/hexrdgui/hexrd/ui/main.py", line 31, in main
    window = MainWindow()
  File "/Users/saransh1/hexrdgui/hexrd/ui/main_window.py", line 77, in __init__
    self.progress_dialog = ProgressDialog(self.ui)
  File "/Users/saransh1/hexrdgui/hexrd/ui/progress_dialog.py", line 13, in __init__
    self.messages_widget = MessagesWidget(self.ui)
  File "/Users/saransh1/hexrdgui/hexrd/ui/messages_widget.py", line 41, in __init__
    self.capture_output()
  File "/Users/saransh1/hexrdgui/hexrd/ui/messages_widget.py", line 67, in capture_output
    self.update_logging_streams()
  File "/Users/saransh1/hexrdgui/hexrd/ui/messages_widget.py", line 85, in update_logging_streams
    HexrdConfig().logging_stdout_stream = sys.stdout
  File "/Users/saransh1/hexrdgui/hexrd/ui/singletons.py", line 23, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
  File "/Users/saransh1/hexrdgui/hexrd/ui/hexrd_config.py", line 239, in __init__
    self.load_default_materials()
  File "/Users/saransh1/hexrdgui/hexrd/ui/hexrd_config.py", line 1101, in load_default_materials
    self.load_materials(str(file_path))
  File "/Users/saransh1/hexrdgui/hexrd/ui/hexrd_config.py", line 685, in load_materials
    self.materials = load_materials_hdf5(f, kev=beam_energy)
  File "/Users/saransh1/hexrdgui/hexrd/ui/hexrd_config.py", line 1220, in _set_materials
    self.prune_overlays()
  File "/Users/saransh1/hexrdgui/hexrd/ui/hexrd_config.py", line 1378, in prune_overlays
    self.overlays = [x for x in self.overlays if x['material'] in mats]
  File "/Users/saransh1/hexrdgui/hexrd/ui/hexrd_config.py", line 1378, in <listcomp>
    self.overlays = [x for x in self.overlays if x['material'] in mats]
KeyError: 'material'```

**Comment by psavery** [comment]
That last line of code where the error is is actually not in master. That was changed as part of the overlay refactor PR. [Here is the new line](https://github.com/HEXRD/hexrdgui/blob/bd5d98bfdeb3b76f7399a13dff1cf6de1b1a7393/hexrd/ui/hexrd_config.py#L1417). Are you sure your hexrdgui is up-to-date?

**Comment by psavery** [comment]
Oh, if you roll back to 0.8.15, then you'll need to start it with `hexrdgui --ignore-settings` so it won't try to load in new settings from the master hexrdgui.

**Comment by saransh13** [comment]
Ok got it. That worked.
