### ISSUE TITLE
Exception in HDF5 (.hexrd) configuration save if panel_buffer is None for any detector

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1161]
Another edge case we'll need to catch.  The HDF5 configuration format needs an array-like panel buffer since HDF5 doesn't support a null type (to my knowledge).  Since the yaml format and the python code support `panel_buffer = None`, we'll need to put a catch in upon write to HDF5.  We have two choices:

1. if `panel_buffer` is `None`, then omit from the write, since the instrument init will assign to `None` if it is not present in the config
2. write a trivial buffer of `np.ones(det.shape, dtype=True)` which functionally leads to the same behavior (though at the cost of having to actually apply the trival buffer mask where applicable)

We'll have to modify the recursion `unwrap_dict_to_h5` to implement 1. to catch `None`.  I'd say 2. is probably easier to implement, if not a bit inelegant.  Thoughts @psavery and @saransh13?

```
Traceback (most recent call last):
  File "/Users/bernier2/Documents/GitHub/hexrd/hexrd/instrument.py", line 3582, in unwrap_dict_to_h5
    grp.create_dataset(key, data=np.atleast_1d(item))
  File "/Users/bernier2/miniconda3/envs/hexrdgui-dev/lib/python3.9/site-packages/h5py/_hl/group.py", line 149, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/Users/bernier2/miniconda3/envs/hexrdgui-dev/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 91, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1663, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1687, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1747, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bernier2/Documents/GitHub/hexrdgui/hexrd/ui/main_window.py", line 326, in on_action_save_config_hexrd_triggered
    self._save_config('.hexrd', 'HEXRD files (*.hexrd)')
  File "/Users/bernier2/Documents/GitHub/hexrdgui/hexrd/ui/main_window.py", line 323, in _save_config
    return HexrdConfig().save_instrument_config(selected_file)
  File "/Users/bernier2/Documents/GitHub/hexrdgui/hexrd/ui/hexrd_config.py", line 715, in save_instrument_config
    instr.write_config(output_file, style=styles[ext])
  File "/Users/bernier2/Documents/GitHub/hexrd/hexrd/instrument.py", line 798, in write_config
    _write_group(f)
  File "/Users/bernier2/Documents/GitHub/hexrd/hexrd/instrument.py", line 793, in _write_group
    unwrap_dict_to_h5(instr_grp, par_dict, asattr=False)
  File "/Users/bernier2/Documents/GitHub/hexrd/hexrd/instrument.py", line 3585, in unwrap_dict_to_h5
    grp.create_dataset(key, data=item)
  File "/Users/bernier2/miniconda3/envs/hexrdgui-dev/lib/python3.9/site-packages/h5py/_hl/group.py", line 149, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/Users/bernier2/miniconda3/envs/hexrdgui-dev/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 57, in make_new_dset
    raise TypeError("One of data, shape or dtype must be specified")
TypeError: One of data, shape or dtype must be specified
```

**Comment by joelvbernier** [comment]
I think the `hexrd` part is fixed by HEXRD/hexrd#403.  We'll just need to fix `panel_buffer_dialog.py`

**Comment by psavery** [comment]
I think this is no longer an issue. At least, I haven't seen it any nobody has reported it in a long time... 🙂
