### ISSUE TITLE
New exception on quit for python 3.9 on Mac os 10.15.7

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1162]
Does this have something to do with #1129?
```
Traceback (most recent call last):
  File "/Users/bernier2/Documents/GitHub/hexrdgui/hexrd/ui/__init__.py", line 31, in eventFilter
    return super().eventFilter(obj, event)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QDialog) already deleted.
Traceback (most recent call last):
  File "/Users/bernier2/Documents/GitHub/hexrdgui/hexrd/ui/__init__.py", line 31, in eventFilter
    return super().eventFilter(obj, event)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QDialog) already deleted.
Traceback (most recent call last):
  File "/Users/bernier2/Documents/GitHub/hexrdgui/hexrd/ui/__init__.py", line 31, in eventFilter
    return super().eventFilter(obj, event)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QDialog) already deleted.
```

**Comment by psavery** [comment]
I didn't get this issue when I tried it just now on Mac.

That stack is unfortunately not very descriptive. It'd be nice if we could figure out a way to get a better error message.

**Comment by psavery** [comment]
Haven't seen this in a while! Gonna close 🙂
