### ISSUE TITLE
Spot exporting error in HEDM --> Fit Grains for multi-detector instruments.

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1192]
Should be easy to find.  This was testing the [multiruby dexela example](https://github.com/HEXRD/examples/tree/master/NIST_ruby/multiruby_dexelas).

```
material:min_sfac_ratio not specified, defaulting to None
	setting the maximum 2theta to instrument maximum: 22.78 degrees
	starting fit on 3 processes with chunksize 1
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/jbernier/miniconda3/envs/hexrdgui/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/jbernier/miniconda3/envs/hexrdgui/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/jbernier/miniconda3/envs/hexrdgui/lib/python3.9/site-packages/hexrd/fitgrains.py", line 100, in fit_grain_FF_reduced
    complvec, results = instrument.pull_spots(
  File "/home/jbernier/miniconda3/envs/hexrdgui/lib/python3.9/site-packages/hexrd/instrument.py", line 1765, in pull_spots
    os.makedirs(output_dir)
  File "/home/jbernier/miniconda3/envs/hexrdgui/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/jbernier/Documents/GitHub/hexrd-examples/NIST_ruby/multiruby_dexelas/include/ff1_0_0'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jbernier/miniconda3/envs/hexrdgui/lib/python3.9/site-packages/hexrd/ui/async_worker.py", line 73, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jbernier/miniconda3/envs/hexrdgui/lib/python3.9/site-packages/hexrd/ui/indexing/run.py", line 419, in run_fit_grains
    self.fit_grains_results = fit_grains(**kwargs)
  File "/home/jbernier/miniconda3/envs/hexrdgui/lib/python3.9/site-packages/hexrd/fitgrains.py", line 393, in fit_grains
    fit_results = pool.map(
  File "/home/jbernier/miniconda3/envs/hexrdgui/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/jbernier/miniconda3/envs/hexrdgui/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
FileExistsError: [Errno 17] File exists: '/home/jbernier/Documents/GitHub/hexrd-examples/NIST_ruby/multiruby_dexelas/include/ff1_0_0'
```

**Comment by psavery** [comment]
@joelvbernier So it looks like the error is because it is trying to make the `ff1_0_0` directory when it already exists. I guess we have two options to fix this:

1. Delete the `ff1_0_0` directory before exporting the spots (this will be bad if there is other output in the directory that we need)
2. Add `exist_ok=True` to `os.makedirs()`. This means it's okay if the directory already exists, and no error is produced.

I'm guessing we should go with 2. This is a change in hexrd.

**Comment by psavery** [comment]
This actually ended up being a race condition for multiprocessing. HEXRD/hexrd#429 fixes it. See the PR for more details.
