### ISSUE TITLE
GUI startup error

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1216]
Both Darren and I started seeing this error after the merge of PR #1208.  I am getting it after loading a session with a single material (CeO2 in this case) and quitting the GUI.  Upone trying to reopen, we get the following exception:
```
Traceback (most recent call last):
  File "/home/jbernier/miniconda3/envs/hexrdgui-dev/bin/hexrdgui", line 33, in <module>
    sys.exit(load_entry_point('hexrdgui', 'gui_scripts', 'hexrdgui')())
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/main.py", line 31, in main
    window = MainWindow()
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/main_window.py", line 79, in __init__
    self.progress_dialog = ProgressDialog(self.ui)
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/progress_dialog.py", line 13, in __init__
    self.messages_widget = MessagesWidget(self.ui)
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/messages_widget.py", line 41, in __init__
    self.capture_output()
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/messages_widget.py", line 67, in capture_output
    self.update_logging_streams()
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/messages_widget.py", line 85, in update_logging_streams
    HexrdConfig().logging_stdout_stream = sys.stdout
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/singletons.py", line 23, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/hexrd_config.py", line 226, in __init__
    self.load_settings()
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/hexrd_config.py", line 400, in load_settings
    self.load_from_state(state)
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/hexrd_config.py", line 356, in load_from_state
    setattr(self, name, value)
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/hexrd_config.py", line 411, in _imported_default_materials
    self.load_default_material(x)
  File "/home/jbernier/Documents/GitHub/hexrdgui/hexrd/ui/hexrd_config.py", line 1187, in load_default_material
    materials[name] = Material(name, file_path)
  File "/home/jbernier/Documents/GitHub/hexrd/hexrd/material.py", line 172, in __init__
    self._readHDFxtal(fhdf=material_file, xtal=name)
  File "/home/jbernier/Documents/GitHub/hexrd/hexrd/material.py", line 651, in _readHDFxtal
    raise IOError('crystal doesn''t exist in material file.')
OSError: crystal doesnt exist in material file.
```

Note that `hexrdgui` is the current prerelease (I have it in developer mode, but same as master):
```
hexrdgui                  0.8.16.dev66+g18f5ba4           dev_0    <develop>
```

**Comment by cjh1** [comment]
@joelvbernier Is this when using hexrd master?

**Comment by cjh1** [comment]
@joelvbernier Can you share your state file?

**Comment by cjh1** [comment]
OK, I can recreate, will take a look

**Comment by psavery** [comment]
I was able to reproduce this issue, and I confirmed that #1218 fixed it.
