### ISSUE TITLE
Pick saving error

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1261]
@psavery -- if you try to perform a Fast Powder calibration while in cartesian view, then you get the following exception:
```
Traceback (most recent call last):
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/async_worker.py", line 73, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/calibration/auto/powder_runner.py", line 99, in run_extract_powder_lines
    self.save_picks_to_overlay()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/calibration/auto/powder_runner.py", line 260, in save_picks_to_overlay
    save_picks_to_overlay(self.active_overlay, self.data_dict)
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/calibration/auto/powder_runner.py", line 281, in save_picks_to_overlay
    hkls = overlay.hkls[det_key]
KeyError: 'Pilatus2M_0_0'
```

**Comment by psavery** [comment]
It looks like this is because, for some reason, the overlay dict just has a `dpanel` detector in the Cartesian view. I am guessing it is getting that because of the fake instrument [here](https://github.com/HEXRD/hexrdgui/blob/a3e45bc324d14560cf574cde5bdb8f28dffd803d/hexrd/ui/calibration/cartesian_plot.py#L142). I will look into this more.
