### ISSUE TITLE
hexrdgui fails to import .cif file

### ISSUE THREAD

**Issue by floriantheuss** [HEXRD/hexrdgui#1272]
when trying to import a cif file by clicking "Import Material" in the Material List Editor I get the following error message (I downloaded the cif file from here: https://materialsproject.org/materials/mp-666): 
Traceback (most recent call last):
  File "C:\Users\Florian\anaconda3\lib\site-packages\hexrd\material.py", line 394, in _readCif
    cif = ReadCif(fcif)
  File "C:\Users\Florian\anaconda3\lib\site-packages\CifFile\CifFile_module.py", line 3107, in ReadCif
    return StarFile.ReadStar(filename,prepared=finalcif,grammar=grammar,scantype=scantype,
  File "C:\Users\Florian\anaconda3\lib\site-packages\CifFile\StarFile.py", line 2174, in ReadStar
    filestream = urlopen(my_uri)
  File "C:\Users\Florian\anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Florian\anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\Florian\anaconda3\lib\urllib\request.py", line 547, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\Users\Florian\anaconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Florian\anaconda3\lib\urllib\request.py", line 1425, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: c>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Florian\anaconda3\lib\site-packages\hexrd\ui\material_list_editor.py", line 78, in import_material
    new_name = HexrdConfig().import_material(selected_file)
  File "C:\Users\Florian\anaconda3\lib\site-packages\hexrd\ui\hexrd_config.py", line 597, in import_material
    material = Material(name, f, kev=beam_energy)
  File "C:\Users\Florian\anaconda3\lib\site-packages\hexrd\material.py", line 180, in __init__
    self._readCif(material_file)
  File "C:\Users\Florian\anaconda3\lib\site-packages\hexrd\material.py", line 396, in _readCif
    raise RuntimeError('OS Error: File not found')
RuntimeError: OS Error: File not found

**Comment by joelvbernier** [comment]
Can you verify which version of hexrdgui you are using?  You can do `conda list` in the env you are running, or if it is from a binary, you can just read the version number directly from the file.

**Comment by saransh13** [comment]
@floriantheuss I was unable to reproduce your error. There was one bug I caught which had to de with the +ve charge on the Uranium ion. PR https://github.com/HEXRD/hexrd/pull/465 fixes that.

**Comment by floriantheuss** [comment]
Hi,

Well first of all thank you for addressing this issue already!
The error I posted occurred on with versions: hexrd 0.8.11, hexrdgui 0.8.9
I ran it on a more recent version (hexrd 0.8.19, hexrdgui 0.8.16), and a
different error popped up (sorry I didn't notice earlier that the two error
messages were different):

*Traceback (most recent call last):*

* File
"C:\Users\Chill\anaconda3\lib\site-packages\hexrd\ui\material_list_editor.py",
line 78, in import_material*

* new_name = HexrdConfig().import_material(selected_file)*

* File
"C:\Users\Chill\anaconda3\lib\site-packages\hexrd\ui\hexrd_config.py", line
748, in import_material*

* material = Material(name, f, kev=beam_energy)*

* File "C:\Users\Chill\anaconda3\lib\site-packages\hexrd\material.py", line
186, in __init__*

* self._readCif(material_file)*

* File "C:\Users\Chill\anaconda3\lib\site-packages\hexrd\material.py", line
616, in _readCif*

* atomtype.append(ptable[ss])*

*KeyError: 'U3+'*
It looks like this is the error you might have just fixed? Let me check,
and I'll let you know.

Best,
Florian

**Comment by floriantheuss** [comment]
quick update: PR https://github.com/HEXRD/hexrd/pull/465 fixes the latest error message

**Comment by joelvbernier** [comment]
Also noticed that these are quite old versions -- due to the pace of development I highly recommend trying out the [latest release ](https://github.com/HEXRD/hexrdgui/releases/tag/0.8.18) :-)
