### ISSUE TITLE
TARDIS import tool

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1320]
Starting TARDIS import tool when the `Intensity Correction > Apply Pixel Solid Angle Correction` option is checked less to error and the GUI is stuck in an infinite loop. Here's a small part of the error I get:

```self.update_norm()
  File "/Users/soderlind3/hexrdgui/hexrd/ui/color_map_editor.py", line 211, in update_norm
    norm = matplotlib.colors.Normalize(vmin=min, vmax=max)
  File "/Users/soderlind3/opt/miniconda3/envs/hexrd/lib/python3.10/site-packages/matplotlib/colors.py", line 1234, in __init__
    self._vmin = _sanitize_extrema(vmin)
RecursionError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/Users/soderlind3/hexrdgui/hexrd/ui/color_map_editor.py", line 82, in range_edited
    self.update_norm()
  File "/Users/soderlind3/hexrdgui/hexrd/ui/color_map_editor.py", line 212, in update_norm
    self.image_object.set_norm(norm)
  File "/Users/soderlind3/hexrdgui/hexrd/ui/image_tab_widget.py", line 259, in set_norm
    self.update_canvas_norms()
  File "/Users/soderlind3/hexrdgui/hexrd/ui/image_tab_widget.py", line 246, in update_canvas_norms
    canvas.set_norm(self.norm)
  File "/Users/soderlind3/hexrdgui/hexrd/ui/image_canvas.py", line 876, in set_norm
    axes_image.set_norm(norm)
  File "/Users/soderlind3/opt/miniconda3/envs/hexrd/lib/python3.10/site-packages/matplotlib/cm.py", line 654, in set_norm
    self.norm = norm
  File "/Users/soderlind3/opt/miniconda3/envs/hexrd/lib/python3.10/site-packages/matplotlib/cm.py", line 613, in norm
    _api.check_isinstance((colors.Normalize, str, None), norm=norm)
RecursionError: maximum recursion depth exceeded in comparison
Traceback (most recent call last):
  File "/Users/soderlind3/hexrdgui/hexrd/ui/color_map_editor.py", line 82, in range_edited
    self.update_norm()
  File "/Users/soderlind3/hexrdgui/hexrd/ui/color_map_editor.py", line 212, in update_norm
    self.image_object.set_norm(norm)
  File "/Users/soderlind3/hexrdgui/hexrd/ui/image_tab_widget.py", line 259, in set_norm
    self.update_canvas_norms()
  File "/Users/soderlind3/hexrdgui/hexrd/ui/image_tab_widget.py", line 246, in update_canvas_norms
    canvas.set_norm(self.norm)
  File "/Users/soderlind3/hexrdgui/hexrd/ui/image_canvas.py", line 876, in set_norm
    axes_image.set_norm(norm)
  File "/Users/soderlind3/opt/miniconda3/envs/hexrd/lib/python3.10/site-packages/matplotlib/cm.py", line 654, in set_norm
    self.norm = norm
  File "/Users/soderlind3/opt/miniconda3/envs/hexrd/lib/python3.10/site-packages/matplotlib/cm.py", line 635, in norm```

**Comment by bnmajor** [comment]
@saransh13 Just having that checked and then opening the LLNL Import Tool does not produce this error for me. Are there additional steps that you took before or after opening the panel?

**Comment by psavery** [comment]
Looks like there is some kind of infinite recursion occurring where the min/max of the color range being changed is causing the min/max of the color range to be changed again.

**Comment by bnmajor** [comment]
@psavery Yes, thanks! I have found the source of the recursion and a fix for it, but in doing so I get the following error:
```
/home/local/KHQ/brianna.major/hexrdgui/hexrd/ui/hexrd_config.py:716: RuntimeWarning: invalid value encountered in true_divide
  images_dict[name] = img / panel.pixel_solid_angles
```
(The error is actually always there, it was just being buried in recursion errors before) Any ideas what is going wrong here?

**Comment by saransh13** [comment]
Must be zeros in `panel.pixel_solid_angles` perhaps?
