### ISSUE TITLE
Tabbed view raising error

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1375]
```Traceback (most recent call last):
  File "/Users/soderlind3/hexrdgui/hexrd/ui/image_tab_widget.py", line 119, in load_images
    self.load_images_tabbed()
  File "/Users/soderlind3/hexrdgui/hexrd/ui/image_tab_widget.py", line 91, in load_images_tabbed
    self.image_canvases[i].load_images(image_names=[name])
  File "/Users/soderlind3/hexrdgui/hexrd/ui/image_canvas.py", line 167, in load_images
    self.update_beam_marker()
  File "/Users/soderlind3/hexrdgui/hexrd/ui/image_canvas.py", line 640, in update_beam_marker
    artist, = axis.plot(*beam_position, **style)
AttributeError: 'NoneType' object has no attribute 'plot'
```

<img width="1045" alt="Screen Shot 2023-03-28 at 9 04 07 AM" src="https://user-images.githubusercontent.com/15834451/228302819-597a1733-cc3c-4c2d-9f67-fd904c4b1678.png">

<img width="1049" alt="Screen Shot 2023-03-28 at 9 04 15 AM" src="https://user-images.githubusercontent.com/15834451/228302844-6f3b0df5-98fc-46ae-a1f9-e6bbc5a9c4cf.png">

**Comment by bnmajor** [comment]
@saransh13 Can you provide the steps you took before you saw this or share a state file? If I just load some data in a select "tabbed view" I am not seeing this error.
