### ISSUE TITLE
Trouble loading saved files

### ISSUE THREAD

**Issue by wehrenberg1** [HEXRD/hexrdgui#1386]
I get this error message when opening saved state:
I reinstalled the 3.10 prerelease today (4/4/2023) and the save file is from Oct 22, so there may be version issues?

Traceback (most recent call last):
  File "C:\Users\wehrenberg1\Anaconda3\envs\hexrdgui\lib\site-packages\hexrd\ui\main_window.py", line 946, in on_action_load_state_triggered
    state.load(h5_file)
  File "C:\Users\wehrenberg1\Anaconda3\envs\hexrdgui\lib\site-packages\hexrd\ui\state.py", line 178, in load
    state = _load_config(h5_file)
  File "C:\Users\wehrenberg1\Anaconda3\envs\hexrdgui\lib\site-packages\hexrd\ui\state.py", line 129, in _load_config
    config_yaml = h5_file[CONFIG_YAML_PATH][()]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\wehrenberg1\Anaconda3\envs\hexrdgui\lib\site-packages\h5py\_hl\group.py", line 305, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'config\\yaml' doesn't exist)"
Traceback (most recent call last):
  File "C:\Users\wehrenberg1\Anaconda3\envs\hexrdgui\lib\site-packages\hexrd\ui\main_window.py", line 946, in on_action_load_state_triggered
    state.load(h5_file)
  File "C:\Users\wehrenberg1\Anaconda3\envs\hexrdgui\lib\site-packages\hexrd\ui\state.py", line 178, in load
    state = _load_config(h5_file)
  File "C:\Users\wehrenberg1\Anaconda3\envs\hexrdgui\lib\site-packages\hexrd\ui\state.py", line 129, in _load_config
    config_yaml = h5_file[CONFIG_YAML_PATH][()]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\wehrenberg1\Anaconda3\envs\hexrdgui\lib\site-packages\h5py\_hl\group.py", line 305, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'config\\yaml' doesn't exist)"

**Comment by psavery** [comment]
@wehrenberg1 Can you send me the state file so I can take a look at it? But indeed, it looks like it is missing some information (although I don't think that was something new added after October 22).

**Comment by saransh13** [comment]
Perhaps you accidentally loaded a `current view` file instead of a state file?

**Comment by psavery** [comment]
Closing this. If it is still an issue, feel free to re-open.
