### ISSUE TITLE
GUI does not accept config files with multiple documents

### ISSUE THREAD

**Issue by donald-e-boyce** [HEXRD/hexrdgui#1402]
This issue arose in the NIST_ruby/single_GE example.

Using the command line, if a config file has multiple documents, then find-grains (and fit-orientations?) will run each document successively. Using the GUI, it fails to load, giving this error:
```
Traceback (most recent call last):
  File "/Users/deboyce/miniconda3/envs/hexrd-dev/lib/python3.10/site-packages/hexrd/ui/main_window.py", line 356, in on_action_open_config_file_triggered
    HexrdConfig().load_instrument_config(str(path))
  File "/Users/deboyce/miniconda3/envs/hexrd-dev/lib/python3.10/site-packages/hexrd/ui/hexrd_config.py", line 873, in load_instrument_config
    self.config['instrument'] = formats[ext]()
  File "/Users/deboyce/miniconda3/envs/hexrd-dev/lib/python3.10/site-packages/hexrd/ui/hexrd_config.py", line 843, in read_yaml
    conf = yaml.load(f, Loader=NumPyIncludeLoader)
  File "/Users/deboyce/miniconda3/envs/hexrd-dev/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/Users/deboyce/miniconda3/envs/hexrd-dev/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/Users/deboyce/miniconda3/envs/hexrd-dev/lib/python3.10/site-packages/yaml/composer.py", line 41, in get_single_node
    raise ComposerError("expected a single document in the stream",
yaml.composer.ComposerError: expected a single document in the stream
  in "/Users/deboyce/Source/hexrd-examples/examples/NIST_ruby/single_GE/docrun/ruby_config.yml", line 1, column 1
but found another document
  in "/Users/deboyce/Source/hexrd-examples/examples/NIST_ruby/single_GE/docrun/ruby_config.yml", line 123, column 1
```

I don't think this feature is used enough to have the GUI do the same thing and run the documents consecutively, but it would be nice if it loaded the first document. Or maybe it could ask the user which document to load, and then the user could run the other documents too, if desired, by reloading.

**Comment by donald-e-boyce** [comment]
Never mind!  I realized that the GUI only accepts instrument config files, not config files for fit-grains or find-orientations. Closing.
