### ISSUE TITLE
Saving Images / Frame Caches from GUI

### ISSUE THREAD

**Issue by darrencpagan** [HEXRD/hexrdgui#1623]
When trying to save a frame cache from a most recent hexrdgui release (1.0.0), I get the following error. I'm not sure what the issue may be here.

```
Traceback (most recent call last):
  File "/nfs/chess/user/dcp99/sw/miniconda/envs/20231029_hexrdgui/lib/python3.11/site-packages/hexrdgui/main_window.py", line 552, in on_action_save_imageseries_triggered
    SaveImagesDialog(self.ui).exec()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/chess/user/dcp99/sw/miniconda/envs/20231029_hexrdgui/lib/python3.11/site-packages/hexrdgui/save_images_dialog.py", line 18, in __init__
    self.parent_dir = HexrdConfig().working_dir
    ^^^^^^^^^^^^^^^
AttributeError: property 'parent_dir' of 'SaveImagesDialog' object has no setter
```

**Comment by bnmajor** [comment]
@darrencpagan This should be fixed in master now!
