### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#1632]
Our packaging runs a single test where it verifies that it can import `hexrdgui` properly, without errors. Currently, there are errors with this test on both Windows and Linux, and they are both Qt6 related. I'm not sure what the problem is yet.

Here is the error for Linux:

```python
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/hexrdgui-package/conda-bld/hexrdgui_1701277637888/test_tmp/run_test.py", line 2, in <module>
    import hexrdgui
  File "/usr/share/miniconda/envs/hexrdgui-package/conda-bld/hexrdgui_1701277637888/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/hexrdgui/__init__.py", line 1, in <module>
    from PySide6.QtCore import QEvent, QObject, Qt
ImportError: /usr/share/miniconda/envs/hexrdgui-package/conda-bld/hexrdgui_1701277637888/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/PySide6/QtCore.abi3.so: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API
```

Here is the error for Windows:

```python
Traceback (most recent call last):

  File "C:\Miniconda\envs\hexrdgui-package\conda-bld\hexrdgui_1701277720458\test_tmp\run_test.py", line 2, in <module>

    import hexrdgui

  File "C:\Miniconda\envs\hexrdgui-package\conda-bld\hexrdgui_1701277720458\_test_env\Lib\site-packages\hexrdgui\__init__.py", line 1, in <module>

    from PySide6.QtCore import QEvent, QObject, Qt

ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.
```

It seems to be some upstream issue.

**Comment by psavery** [comment]
Fixed by: #1633
