### ISSUE TITLE
Loading in Calibration File

### ISSUE THREAD

**Issue by JoshuaWard201** [HEXRD/hexrdgui#1720]
I am running the hexrd gui on a Windows machine. I am attempting to load in a .yml calibration file for the Dexela dual panel detectors.  When I use File -> Open -> Instrument -> File, and select the "CalFile.yml' the gui freezes, and I get the following error:

Exception in thread Thread-1 (_handle_workers):
Traceback (most recent call last):
  File "C:\Users\wardjt\.conda\envs\hexrd_gui\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\wardjt\.conda\envs\hexrd_gui\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\wardjt\.conda\envs\hexrd_gui\Lib\multiprocessing\pool.py", line 522, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "C:\Users\wardjt\.conda\envs\hexrd_gui\Lib\multiprocessing\pool.py", line 502, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "C:\Users\wardjt\.conda\envs\hexrd_gui\Lib\multiprocessing\connection.py", line 896, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wardjt\.conda\envs\hexrd_gui\Lib\multiprocessing\connection.py", line 828, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at most 63 handles, got a sequence of length 66

I then have to ctrl+c to get out of it

**Comment by JoshuaWard201** [comment]
@psavery could you advise?

**Comment by psavery** [comment]
Hey @JoshuaWard201, sorry for the delay. Can you send me this yaml file? If you can post it in this issue, that will be fine. If you cannot post it publicly, can you email it to me instead?

**Comment by JoshuaWard201** [comment]
Hey @psavery, sending to your email.
