### ISSUE TITLE
IndexError when delete last detector

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#287]
```
Traceback (most recent call last):
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/color_map_editor.py", line 56, in update_bounds
    bounds = self.percentile_range()
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/color_map_editor.py", line 66, in percentile_range
    l = min([np.percentile(d[key], low) for key in d.keys()])
ValueError: min() arg is an empty sequence
Traceback (most recent call last):
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/load_panel.py", line 166, in switch_detector
    self.ui.transform.setCurrentIndex(self.state['trans'][self.idx])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/main_window.py", line 213, in on_detectors_changed
    self.load_widget.config_changed()
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/load_panel.py", line 160, in config_changed
    self.enable_read()
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/load_panel.py", line 398, in enable_read
    if self.state['dark'][self.idx] == 4 and self.dark_files is not None:
IndexError: list index out of range
```

**Comment by psavery** [comment]
So, is this if you delete the detectors by pressing the minus button on the form view? I thought I had put in something to prevent you from deleting all of the detectors...

**Comment by cjh1** [comment]
Yes, the minus button with a single detector.
