### ISSUE TITLE
Polar view error with hexrd master

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#321]
With the [current hexrd master](https://github.com/HEXRD/hexrd/tree/031d348dd27661d22d726dfdd4cc0838ca73a38b), there is an error in hexrdgui if you try to display the polar view for our tiff image 4-detector ge example. I am not sure what may have changed to cause this.

The error is pasted below.

```
Traceback (most recent call last):
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/async_worker.py", line 73, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/calibration/polar_plot.py", line 14, in polar_viewer
    return InstrumentViewer()
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/calibration/polar_plot.py", line 32, in __init__
    self.draw_polar()
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/calibration/polar_plot.py", line 51, in draw_polar
    self.pv.warp_all_images()
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/calibration/polarview.py", line 247, in warp_all_images
    self.create_warp_image(det)
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/calibration/polarview.py", line 209, in create_warp_image
    self.warp_dict[det] = panel.interpolate_bilinear(
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/instrument.py", line 2061, in interpolate_bilinear
    + (ij_frac[:, 1] - j_floor)*img[i_floor, j_ceil]
IndexError: index 2048 is out of bounds for axis 1 with size 2048
```

**Comment by joelvbernier** [comment]
Ok, figured this out.  I added an attribute on the detector panels to hold the buffer/mask that defaults to `None`; the routines that clip points to the panel extent uses the panel_buffer attribute.  This probably needs a bit more thought.  Anyhow, if you add a "buffer: <nonzero float in mm>" line in the instrument config, it works (see TARDIS example below).

This attribute in the yml file obviously leaves something to be desired if the buffer is an mask array (will currently print it out as a flattened list!).

Might need to consider migrating the instrument config to something more amenable to storing arrays, like HDF5?  

```
beam:
  energy: 10.2505
  vector:
    azimuth: 60.699183006872545
    polar_angle: 90.17486338797815
calibration_crystal:
  grain_id: 0
  inv_stretch:
  - 1.0
  - 1.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  orientation:
  - 0.
  - 0.
  - -0.30892328
  position:
  - 0.0
  - 0.0
  - 0.0
detectors:
  IP2:
    pixels:
      columns: 900
      rows: 420
      size:
      - 0.1
      - 0.1
    buffer: 0.5
    saturation_level: 16535
    transform:
      tilt:
      - 2.7204811846010155e-16
      - 2.221441469079183
      - 2.221441469079183
      translation:
      - -0.21677323042971464
      - -11.5151901708
      - -25.036701450383205
  IP4:
    pixels:
      columns: 900
      rows: 420
      size:
      - 0.1
      - 0.1
    buffer: 0.5
    saturation_level: 16535
    transform:
      tilt:
      - -1.9236706937217895e-16
      - -2.221441469079183
      - 2.221441469079183
      translation:
      - 0.4848128268853955
      - 11.720155224227199
      - -24.27060023593645
id: N200603-001
oscillation_stage:
  chi: 0.0
  translation:
  - 0.0
  - 0.0
  - 0.075
```

**Comment by joelvbernier** [comment]
will close for now, with the caveat that the panel buffer needs some more thought.

**Comment by joelvbernier** [comment]
@psavery you get it to work?

**Comment by psavery** [comment]
Heading out for the weekend. I'll try it out on Monday :slightly_smiling_face:

**Comment by joelvbernier** [comment]
I should mention we can hijack the buffers internally to the GUI if it comes in as `None`.

**Comment by psavery** [comment]
@joelvbernier I think this is working fine. Is a default panel buffer of `0.5` good for the GUI, if it isn't specified in the config? The images seem to be coming out fine.
