### ISSUE TITLE
Exception when added overlay

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#500]
```python
Traceback (most recent call last):
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/image_canvas.py", line 282, in update_overlays
    self.iviewer.update_overlay_data()
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/calibration/raw_iviewer.py", line 17, in update_overlay_data
    update_overlay_data(self.instr, self.type)
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/overlays/__init__.py", line 90, in update_overlay_data
    overlay['data'] = generator.overlay(display_mode)
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/overlays/powder_diffraction.py", line 46, in overlay
    indices, ranges = self.plane_data.getMergedRanges()
  File "/home/cjh/work/source/hexrd/hexrd/crystallography.py", line 957, in getMergedRanges
    (tThRanges[:-1, 1] < tThRanges[1:, 0], True)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by joelvbernier** [comment]
I think this is happening because no rings are selected in the planeData.exclusions by default.  We can make sure that at least the first one is set to True, and that should fix it￼.

**Comment by joelvbernier** [comment]
@saransh13 and @psavery, this is still happening.  Can we make sure the planeData object in the material has at least the first exclusion set to False?  For reference, we used the first 5 as a default "active" set in the old GUI when we instantiated a material object.

```
Traceback (most recent call last):
  File "/home/joelvbernier/Documents/GitHub/hexrdgui/hexrd/ui/main_window.py", line 828, in update_all
    self.ui.image_tab_widget.load_images()
  File "/home/joelvbernier/Documents/GitHub/hexrdgui/hexrd/ui/image_tab_widget.py", line 119, in load_images
    self.load_images_untabbed()
  File "/home/joelvbernier/Documents/GitHub/hexrdgui/hexrd/ui/image_tab_widget.py", line 99, in load_images_untabbed
    self.image_canvases[0].load_images(
  File "/home/joelvbernier/Documents/GitHub/hexrdgui/hexrd/ui/image_canvas.py", line 151, in load_images
    self.update_overlays()
  File "/home/joelvbernier/Documents/GitHub/hexrdgui/hexrd/ui/image_canvas.py", line 308, in update_overlays
    self.iviewer.update_overlay_data()
  File "/home/joelvbernier/Documents/GitHub/hexrdgui/hexrd/ui/calibration/raw_iviewer.py", line 17, in update_overlay_data
    update_overlay_data(self.instr, self.type)
  File "/home/joelvbernier/Documents/GitHub/hexrdgui/hexrd/ui/overlays/__init__.py", line 91, in update_overlay_data
    overlay['data'] = generator.overlay(display_mode)
  File "/home/joelvbernier/Documents/GitHub/hexrdgui/hexrd/ui/overlays/powder_diffraction.py", line 83, in overlay
    indices, ranges = self.plane_data.getMergedRanges()
  File "/home/joelvbernier/Documents/GitHub/hexrd/hexrd/crystallography.py", line 974, in getMergedRanges
    (tThRanges[:-1, 1] < tThRanges[1:, 0], True)
IndexError: too many indices for array
```

**Comment by joelvbernier** [comment]
I fact, when I fire up the GUI from a previous state where an overlay was selected, this exception prevents me from loading a set of images via the `File --> Open --> Images` dialog.  

In addition, when I open the hkls table for the default materials as loaded, they are empty; I have to change an interactor to trigger regen to see them (_e.g._ dmin), and I have to do this for each material to populate the table.
![no_hkls](https://user-images.githubusercontent.com/1154130/94083501-297ba400-fdb8-11ea-84dc-f9ca7f29cd8f.png)

**Comment by psavery** [comment]
@joelvbernier I think the last comment might actually be caused by a different bug, and that one is now up in #570.

**Comment by saransh13** [comment]
@joelvbernier @psavery I did a PR in `hexrd` the first `hkl` reflection always has `exclusion` set to `False` by default.

**Comment by psavery** [comment]
@saransh13 That sounds great, thanks!
