### ISSUE TITLE
Exception when closing app after applying mask to polar view

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#548]
```
Exception ignored in: <function ZoomCanvas.__del__ at 0x7f21677dd310>
Traceback (most recent call last):
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/zoom_canvas.py", line 34, in __del__
    self.cleanup()
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/zoom_canvas.py", line 38, in cleanup
    self.remove_overlay_lines()
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/zoom_canvas.py", line 46, in remove_overlay_lines
    self.box_overlay_line.remove()
AttributeError: 'NoneType' object has no attribute 'remove'

```

**Comment by bnmajor** [comment]
@cjh1 This seems to be related to the `zoom canvas` and may end up being a non-issue since @joelvbernier has requested that we remove the picker window for hand-drawn masks in #474

**Comment by psavery** [comment]
I think this should be fixed now. The cleanup methods now check if the objects are `None` before cleaning them up.
