### ISSUE TITLE
Exception when switching from plolar to raw with mask applied

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#585]
```python
Traceback (most recent call last):
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/main_window.py", line 713, in change_image_mode
    self.update_all()
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/main_window.py", line 831, in update_all
    line_data = convert_polar_to_raw(data)
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/create_raw_mask.py", line 45, in convert_polar_to_raw
    cart = panel.angles_to_cart(np.radians(l))
  File "/home/cjh/work/source/hexrd/hexrd/instrument.py", line 2170, in angles_to_cart
    angs = np.hstack([tth_eta, np.zeros((len(tth_eta), 1))])
  File "<__array_function__ internals>", line 5, in hstack
  File "/home/cjh/.virtualenvs/hexrd/lib/python3.8/site-packages/numpy/core/shape_base.py", line 344, in hstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)


```

**Comment by joelvbernier** [comment]
fix with an `np.atleast_2d`?
