### ISSUE TITLE
error in hexrdgui: looking for silx package

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#640]
This was after a fresh install in a new conda environment. Starting `hexrdgui` for the first time leads to this error. I had to do a `pip install silx` to fix this.

```Traceback (most recent call last):
  File "/Users/saransh1/anaconda3/envs/gui/bin/hexrdgui", line 33, in <module>
    sys.exit(load_entry_point('hexrdgui', 'gui_scripts', 'hexrdgui')())
  File "/Users/saransh1/anaconda3/envs/gui/bin/hexrdgui", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/saransh1/anaconda3/envs/gui/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/saransh1/anaconda3/envs/gui/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/saransh1/hexrd/hexrd/__init__.py", line 3, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
  File "/Users/saransh1/anaconda3/envs/gui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/Users/saransh1/anaconda3/envs/gui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/Users/saransh1/anaconda3/envs/gui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/saransh1/anaconda3/envs/gui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/Users/saransh1/anaconda3/envs/gui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/saransh1/anaconda3/envs/gui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'silx' distribution was not found and is required by hexrdgui
```

**Comment by joelvbernier** [comment]
Are you in dev mode?  @cjh1 is this a problem silimar to `pyhdf`, because I see it is a dependency in the conda recipe as of #611

**Comment by cjh1** [comment]
@saransh13 How are you trying to install?

**Comment by saransh13** [comment]
Installed using conda. Just followed the recipe on the github page. I'm in dev mode.

**Comment by joelvbernier** [comment]
Are you installing the latest conda package?  0.8? Or just updating an existing (older) installation live?  @cjh1: it should be packaged with the latest, yes?

**Comment by cjh1** [comment]
Yes, its [installed](https://github.com/HEXRD/hexrdgui/blob/master/conda.recipe/meta.yaml#L29) in the latest and 0.8

**Comment by joelvbernier** [comment]
@saransh13 -- can you verify the package version you installed?  If it was an older release (not the pre-release channel), then it would not have had the silx package.

**Comment by psavery** [comment]
I think this is fixed... 🙂
