### ISSUE TITLE
Exception running fit-grains process

### ISSUE THREAD

**Issue by johnkit** [HEXRD/hexrdgui#643]
An error occurs when running grain fitting from hexrdgui. To reproduce:

* Load the multiruby_dexelas images (from the hexrdgui menu)
* Run indexing with min/max values of 7000/7001
* When the Fit Grains Options Dialog appears, click the "Fit Grains" button
* After some time (less than a minute on my MacBook Pro), the following error is written to the console:

```
Range to be used:  0.0  ->  5.0
Range to be used:  0.0  ->  546.1610000003129
Indexing complete
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/john/projects/hexrd/dev/hexrd/hexrd/fitgrains.py", line 235, in fit_grain_FF_reduced
    np.vstack([np.r_[x[7], x[6][-1]] for x in presults])
  File "<__array_function__ internals>", line 5, in vstack
  File "/Users/john/projects/hexrd/dev/venv-hexrd/lib/python3.8/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/john/projects/hexrd/dev/hexrdgui/hexrd/ui/async_worker.py", line 73, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/john/projects/hexrd/dev/hexrdgui/hexrd/ui/indexing/run.py", line 216, in run_fit_grains
    self.fit_grains_results = fit_grains(config, grains_table, write_spots_files=False)
  File "/Users/john/projects/hexrd/dev/hexrd/hexrd/fitgrains.py", line 384, in fit_grains
    fit_results = pool.map(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: need at least one array to concatenate
2020-10-12 14:22:50.895 Python[52049:3030793] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
```

**Comment by johnkit** [comment]
With an older/dev version of hexrdgui, the error only occurred when the eta-omega maps were generated the in the same hexrdgui session as grain fitting. However the problem now occurs whether the eta-omega maps are generated or loaded.

**Comment by psavery** [comment]
It looks like it is happening for me because the `culled_results` [here](https://github.com/HEXRD/hexrd/blob/2ee9f3bcb42ed4328b930dd68acf65da7e127125/hexrd/fitgrains.py#L183) for one of the detectors (ff1_0_1) is getting set to an empty list.

The error is complaining that there is no data to concatenate.

**Comment by psavery** [comment]
I was able to fix it by taking into account that the `presults` might be empty, by inserting the following code [here](https://github.com/HEXRD/hexrd/blob/2ee9f3bcb42ed4328b930dd68acf65da7e127125/hexrd/fitgrains.py#L230):

```python
            if not presults:
                culled_results_r[det_key] = []
                continue
```

However, I should double-check if it is reasonable for `presults` to be empty to begin with.
