### ISSUE TITLE
Ensure hkls of loaded eta omega maps match that in the GUI

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#646]
Currently, for the indexing, the user can load eta omega map files that do not have the same HKLs (or maybe not even the same material) as that in the GUI.

With this mismatch, the indexing runs fine, but a key error will occur when the user tries to run grain fitting, that looks like this:
```python
Traceback (most recent call last):
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/async_worker.py", line 73, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/indexing/run.py", line 171, in run_fit_grains
    min_samples, mean_rpg = create_clustering_parameters(config,
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/findorientations.py", line 581, in create_clustering_parameters
    seed_hkl_ids = [
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/findorientations.py", line 582, in <listcomp>
    plane_data.hklDataList[active_hkls[i]]['hklID']
IndexError: list index out of range
```

It might be nice to ensure the HKLs of the loaded eta omega maps match, because this is otherwise a little bit of an obscure error for the user, and they may not realize what the problem is.

**Comment by psavery** [comment]
This is probably less important as of #832, because the user explicitly selects the material they are using. I guess it will be their responsibility to make sure the material used to generate the eta omega maps and the material they are using for indexing/grain fitting are the same.
