### ISSUE TITLE
Current master broken

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#663]
Looks like something got broken in the materials tab, possibly some PR's out of sync:
```
(hexrdgui) PS C:\Users\berni\Documents\GitHub> python .\hexrdgui\hexrd\ui\main.py
Traceback (most recent call last):
  File ".\hexrdgui\hexrd\ui\main.py", line 8, in <module>
    from hexrd.ui.main_window import MainWindow
  File "c:\users\berni\onedrive\documents\github\hexrdgui\hexrd\ui\main_window.py", line 38, in <module>
    from hexrd.ui.materials_panel import MaterialsPanel
  File "c:\users\berni\onedrive\documents\github\hexrdgui\hexrd\ui\materials_panel.py", line 12, in <module>
    from hexrd.ui.material_properties_editor import MaterialPropertiesEditor
  File "c:\users\berni\onedrive\documents\github\hexrdgui\hexrd\ui\material_properties_editor.py", line 4, in <module>
    from hexrd.unitcell import _StiffnessDict
ImportError: cannot import name '_StiffnessDict' from 'hexrd.unitcell' (C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\hexrd-0.7.12.dev207+g52f8fa7-py3.8-win-amd64.egg\hexrd\unitcell.py)
```

For ref, hexrdgui is at
```
commit 8c006bf33432c084cd5cf6de7b5d50927a590e9c (HEAD -> master, origin/master,
origin/HEAD)
Merge: 1111d1f b203601
Author: Patrick Avery <patrick.avery@kitware.com>
Date:   Thu Nov 19 09:13:49 2020 -0600

    Merge pull request #660 from psavery/fix-equivalent-stress

    Fix equivalent stress computation
```

and hexrd is at
```
commit 261b3c99fc11b48bcc89122c2d9596cc9b4cb854 (HEAD -> master, origin/master,
origin/HEAD)
Author: Saransh <saransh1@llnl.gov>
Date:   Wed Nov 25 10:10:18 2020 -0800

    adding updatespectrum function which updates the spectrum based on the value
s in the LeBail.parameter class. Only parameters which are set to vary = True wi
ll be considered.
```

**Comment by psavery** [comment]
@joelvbernier The `_StiffnessDict` is [here](https://github.com/HEXRD/hexrd/blob/master/hexrd/unitcell.py#L1635) on the master branch. It looks like it is there, so I'm not sure why are you getting the error. Maybe you need to make sure you did an editable pip environment for hexrd? (`pip install -e`)?

An `f` was added to the name (`_StifnessDict` -> `_StiffnessDict`) in [this commit](https://github.com/HEXRD/hexrd/commit/8462654520e7e6cf8201ebaa015ecbde58cac5c8#diff-cc8fe590f45e0bd5bd6fe3aae721c34631952e766d32ea9a29ec4443ae7c75ddR1625) on master.
