### ISSUE TITLE
Load Series of tiff files

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#722]
We need to support the ability to load stacks of tiff images for detectors so that imageseries can be created from scratch. To do this we need a widget to allow the user to select the directory and files that should be used and to set the relevant data for the detector. Below is a mock-up of what this dialog could look like:

![yaml_form](https://user-images.githubusercontent.com/51238406/105758738-9a28fd80-5f1d-11eb-8027-6e56bce79b0d.png)

Where:

- `Empty Frames` specifies the number of frames to skip at the beginning (default to 0)
- `Max File Frames` specifies the maximum number of frames to read in each file, if there are multiple frames (default to 1)
- `Max Total Frames` specifies the maximum number of frames to be read in total, in the event that you need to skip frames at the end (default to number of matching files * max-file-frames)
- `Omega` has two input options
  - `Load from File` allows you to select a file that contains the omega data
  - Manually enter values allows you to enter values by hand
    - `Minimum` is required as well as either `Maximum` OR `Delta` - whichever value is not provided will be automatically calculated from the other two.

**Comment by joelvbernier** [comment]
Looks good, although the defaults for `'max-total-frames'` and `'max-file-frames'` are both 0, which means read all available.

**Comment by joelvbernier** [comment]
We do not currently support negative delta omega in `imageseries`, but I think I'll make a feature request issue to do so (what do you think @donald-e-boyce?)

**Comment by donald-e-boyce** [comment]
I think that is a good idea. It shouldn't be too hard to do. We just
have to check in a number of places for impact.

**Comment by joelvbernier** [comment]
@bnmajor -- noticed a bug in Load Data related to this.

Take the images in the shared Google Drive folder under sample_images:
- RUBY_4537.ge
- RUBY_4537.ge

These are raw GE format files (can use the instrument config [here](https://github.com/HEXRD/examples/blob/master/NIST_ruby/single_GE/include/ge_detector.yml) with them) that each have 482 data frames: 2 empty to skip at the start, and 480 data frames.  The associated omega for the composite scan are (-60, 0), (0, 60) in 0.25 steps.  When I try to index I get the following stack trace:
```
Traceback (most recent call last):
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/indexing/run.py", line 78, in ome_maps_selected
    config = create_indexing_config()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/indexing/create_config.py", line 51, in create_indexing_config
    ImageLoadManager().add_omega_metadata(load_omegas_dict)
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_load_manager.py", line 330, in add_omega_metadata
    ims_dict[key].metadata['omega'] = omw.omegas
  File "/Users/joel/Documents/GitHub/hexrd/hexrd/imageseries/omega.py", line 145, in omegas
    raise OmegaSeriesError(msg)
hexrd.imageseries.omega.OmegaSeriesError: 'number of frames (482) does not match number of wedge frames (480)'
``` 
which indicates that the omegas are likely getting generated properly, but the 'image-files' spec to load these data is not.  The proper YAML spec to load the raw is as follows:
```
image-files:
  directory: /Users/Shared/example_analysis/raw_data
  files: "RUBY_4537.ge
RUBY_4538.ge"

options:
  empty-frames: 2
  max-frames: 0
meta:
  panel: ge
```
which should correspond to the table entries
![Screen Shot 2021-01-28 at 12 40 31 PM](https://user-images.githubusercontent.com/1154130/106196228-05fda700-6166-11eb-94da-8a4994c5a4bc.png)
What might not be clear is that the `empty-frames` skipping is applied to every file in the list (we don't have a global option at the present to only skip at the start of the first file because we haven't needed it).  Anyhow, this give the proper length imageseries when I load directly:
```
In [4]: ims = imageseries.open("raw_images_RUBY_000000-GE.yml", format='image-files')

In [5]: len(ims)
Out[5]: 480
```
Just an error in the read of the table data?  Of course the form we are discussing adding here allows us to be more explicit, but for scans comprised of ~1-6 multi-frame image files, the existing Load Data widget makes it easy to get going.

**Comment by bnmajor** [comment]
#732 provides a load dialog for stacks of images as well as provides a fix for the bug described here.

**Comment by bnmajor** [comment]
This comment was originally made [here](https://github.com/HEXRD/hexrdgui/issues/758#issuecomment-790393437) but I'm adding it to this issue since this is the one it pertains to.

> Reopening this issue due to the following bugs:
> 
> 1. If I try to load a single image (through the widget) after successfully loading a big series of files, it looks like the omega wedges are not getting reset, which leads to the following:
> 
> ```
> Traceback (most recent call last):
>   File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\async_worker.py", line 73, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_load_manager.py", line 199, in process_ims
>     self.add_omega_metadata(HexrdConfig().imageseries_dict)
>   File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_load_manager.py", line 343, in add_omega_metadata
>     ims_dict[key].metadata['omega'] = omw.omegas
>   File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\hexrd\imageseries\omega.py", line 145, in omegas
>     raise OmegaSeriesError(msg)
> hexrd.imageseries.omega.OmegaSeriesError: 'number of frames (1) does not match number of wedge frames (240)'
> ```
> 
> 1. I have an example with two empty frames, and if I enter the omega metadata properly in the Load Data widget, I get an `OmegaImageSeriesError` when I attempt to generate eta-ome maps (which requires those data); observe
>    ![Screen Shot 2021-03-03 at 22 47 07](https://user-images.githubusercontent.com/1154130/109922579-6bb3e600-7c72-11eb-94ff-5e42acfa768d.png)
> 
> ```
> Traceback (most recent call last):
>   File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/indexing/run.py", line 85, in ome_maps_selected
>     config = create_indexing_config()
>   File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/indexing/create_config.py", line 51, in create_indexing_config
>     ImageLoadManager().add_omega_metadata(load_omegas_dict)
>   File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_load_manager.py", line 343, in add_omega_metadata
>     ims_dict[key].metadata['omega'] = omw.omegas
>   File "/Users/joel/Documents/GitHub/hexrd/hexrd/imageseries/omega.py", line 145, in omegas
>     raise OmegaSeriesError(msg)
> hexrd.imageseries.omega.OmegaSeriesError: 'number of frames (480) does not match number of wedge frames (484)'
> ```
> 
> It _should_ be using the omega start, omega stop, and nsteps to generate the omega wedges, but it is somehow using the total number of frames in the file (ignoring the 2 empty frames I've specified).
> 3. the Stack import seems to be similarly misbehaving, ignoring the specification of empty frames. It seems like we have to revisit how the `image-files` options are handled. For ref (@bnmajor) the documentation is [here](https://github.com/HEXRD/hexrd/wiki/ims-load-options#keyword-options-for-imageseries).
> ![Screen Shot 2021-03-03 at 23 17 00](https://user-images.githubusercontent.com/1154130/109925511-b6376180-7c76-11eb-85d6-b41a38bbfd23.png)
> ![Screen Shot 2021-03-03 at 23 08 30](https://user-images.githubusercontent.com/1154130/109924613-64420c00-7c75-11eb-98e4-47ffdc7cda5c.png)
> 4. While I am having trouble recreating it, I was seemingly getting an error when importing omega wedges that sum to < 360°; while it is true that the wedges cannot sum to > 360°, we often have scan ranges that sum to less.
> 
> There is an example stack that should help your testing on the shared drive under "sample_images":
> 
> * RUBY_4537.ge, 242 total frames, 2 empty (at the start), range is -60°, 0° in 240 steps (0.25° delta)
> * RUBY_4538.ge, 242 total frames, 2 empty (at the start), range is 0°, 60° in 240 steps (0.25° delta)
> 
> The yaml spec to read them is:
> 
> ```
> image-files:
>   directory: ../raw_data
>   files: "RUBY_4537.ge
> RUBY_4538.ge"
> 
> options:
>   empty-frames: 2
>   max-frames: 0
> 
> meta:
>   panel: ge
> ```

**Comment by bnmajor** [comment]
Some fixes that need to be made before this can be closed:
- [ ] Change names of widgets in UI to match yaml keys
- [ ] Set the number of frames for omega wedges from the length of the imageseries
