### ISSUE TITLE
hexrdgui overwriting hexrd.constants on Windows

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#757]
Very strange bug indeed here I am getting on Windows.

I made an environment for the hexrdgui and installed the prerelease conda package.  I think linked to the local repo using
```
pip install --no-deps -U -e hexrd
set CONDA_BUILD=1
pip install --no-deps -U -e hexrdgui
```
after running the GUI and quitting, upon attempting to re-run the GUI I get the following:
```
(hexrdgui) PS C:\Users\berni\Documents\GitHub> python .\hexrdgui\hexrd\ui\main.py
Traceback (most recent call last):
  File ".\hexrdgui\hexrd\ui\main.py", line 8, in <module>
    from hexrd.ui.main_window import MainWindow
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\main_window.py", line 12, in <module>
    from hexrd.ui.calibration_config_widget import CalibrationConfigWidget
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\calibration_config_widget.py", line 9, in <module>
    from hexrd.ui import constants
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\constants.py", line 7, in <module>
    WAVELENGTH_TO_KEV = constants.keVToAngstrom(1.)
AttributeError: module 'hexrd.constants' has no attribute 'keVToAngstrom'
```
upon further inspection, I find that hexrd/constants.py has been modified; specifically emptied ?!
```
(hexrdgui) PS C:\Users\berni\Documents\GitHub\hexrd> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   hexrd/constants.py

no changes added to commit (use "git add" and/or "git commit -a")
(hexrdgui) PS C:\Users\berni\Documents\GitHub\hexrd> more .\hexrd\constants.py

(hexrdgui) PS C:\Users\berni\Documents\GitHub\hexrd>
```
Note that I _have not_ modified anything in hexrd, but simple run, then rerun `hexrdgui`.

**Comment by joelvbernier** [comment]
Just to illustrate:
```
(hexrdgui) PS C:\Users\berni\Documents\GitHub\hexrd> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
(hexrdgui) PS C:\Users\berni\Documents\GitHub\hexrd> cd ..
(hexrdgui) PS C:\Users\berni\Documents\GitHub> python .\hexrdgui\hexrd\ui\main.py
(hexrdgui) PS C:\Users\berni\Documents\GitHub> cd .\hexrd\
(hexrdgui) PS C:\Users\berni\Documents\GitHub\hexrd> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   hexrd/constants.py

no changes added to commit (use "git add" and/or "git commit -a")
```
The gui did open normally, I quit it, and then found constants modified.

**Comment by joelvbernier** [comment]
I confirmed that simply running the GUI is clobbering `hexrd/hexrd/constants.py`.

**Comment by psavery** [comment]
@joelvbernier I'm 95% sure I know what the problem is. I'll fix it later today.

**Comment by joelvbernier** [comment]
Path mangling?

**Comment by psavery** [comment]
I put up a PR at hexrd/hexrd#182 and explained it there.

**Comment by psavery** [comment]
@joelvbernier I was able to reproduce this issue as you described it, and I also tested hexrd/hexrd#182 and confirmed that it fixes the issue.
