### ISSUE TITLE
Reset colormap input min to 1 in log scale to avoid ValueError

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#857]
if log scale gets checked, and the min colormap value is 0, you get a value error in the terminal
```
Traceback (most recent call last):
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\color_map_editor.py", line 133, in update_norm
    self.image_object.set_norm(norm)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_tab_widget.py", line 237, in set_norm
    self.update_canvas_norms()
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_tab_widget.py", line 229, in update_canvas_norms
    canvas.set_norm(self.norm)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_canvas.py", line 656, in set_norm
    self.draw()
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\backends\backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\cbook\deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\axes\_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\image.py", line 643, in draw
    im, l, b, trans = self.make_image(
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\image.py", line 928, in make_image
    return self._make_image(self._A, bbox, transformed_bbox, clip,
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\image.py", line 547, in _make_image
    output = self.norm(resampled_masked)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\colors.py", line 1192, in __call__
    self._check_vmin_vmax()
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\colors.py", line 1181, in _check_vmin_vmax
    raise ValueError("minvalue must be positive")
ValueError: minvalue must be positive
```
Would it be possible to modify the minimum value of the colormap to 1 when log scale is checked?

**Comment by psavery** [comment]
Hmm, strange. There is a check in there already for that [here](https://github.com/HEXRD/hexrdgui/blob/8abd42a0fca9830a85985b01841f30d5dc3def6e/hexrd/ui/color_map_editor.py#L127-L129). It looks like the call stack is from within that function as well. I wonder why it didn't work?

**Comment by psavery** [comment]
Can you give me the data you used to cause this error so I can reproduce it and figure out why that check isn't working?

**Comment by joelvbernier** [comment]
Now includes #1120
