### ISSUE TITLE
Reduced parameter length mismatch in Powder Calibration if lattice parameter(s) are checked

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#859]
I accidentally left the lattice parameter checked to refine while using the calibrator and got the following `ValueError`
```
Traceback (most recent call last):
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\async_worker.py", line 73, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\calibration\auto\powder_runner.py", line 162, in run_calibration
    ic.run_calibration(**kwargs)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\calibration\auto\instrument_calibrator.py", line 53, in run_calibration
    resd0 = obj_func(x0, data_dict)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\calibration\auto\powder_calibrator.py", line 344, in residual
    return self._evaluate(reduced_params, data_dict)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\calibration\auto\powder_calibrator.py", line 302, in _evaluate
    full_params[self.flags] = reduced_params
ValueError: NumPy boolean array indexing assignment cannot assign 2 input values to the 3 output values where the mask is true
```
Time to go check where it is getting the parameters/flags.  Maybe best to just write an `update` method on the `PowderCalibrator' class?

**Comment by psavery** [comment]
Looks like this is the same as #855

**Comment by psavery** [comment]
It looks to me that this is caused by the `InstrumentCalibrator` [passing reduced flags to the residual function](https://github.com/HEXRD/hexrdgui/blob/8abd42a0fca9830a85985b01841f30d5dc3def6e/hexrd/ui/calibration/auto/instrument_calibrator.py#L49-L53), but the [flags in the `PowderCalibrator` class are full length](https://github.com/HEXRD/hexrdgui/blob/8abd42a0fca9830a85985b01841f30d5dc3def6e/hexrd/ui/calibration/auto/powder_calibrator.py#L24-L26).

The reduced length flags does not include lattice parameter refinements.

So, when any of the lattice parameter refinements are `True`, the number of `True` items in `self.flags` [here](https://github.com/HEXRD/hexrdgui/blob/8abd42a0fca9830a85985b01841f30d5dc3def6e/hexrd/ui/calibration/auto/powder_calibrator.py#L302) won't match the shape of the reduced params it received from the `InstrumentCalibrator. Hence the error.
