### ISSUE TITLE
Sigh...  GUI should self-correct if trying to load an image with 0 values in log scale

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#878]
currently, if you load an image with pixels values <=0 you get a `ValueError` if `log scale` is checked.  That checkbox callback function should properly offset images to be amenable to log scaling to prevent this (subtract the non-nan min and add 1).
```
Traceback (most recent call last):
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\main_window.py", line 651, in deep_rerender
    self.update_all(clear_canvases=True)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\main_window.py", line 696, in update_all
    self.ui.image_tab_widget.load_images()
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_tab_widget.py", line 119, in load_images
    self.load_images_untabbed()
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_tab_widget.py", line 99, in load_images_untabbed
    self.image_canvases[0].load_images(
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_canvas.py", line 154, in load_images
    self.show_saturation()
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_canvas.py", line 414, in show_saturation
    self.clear_saturation()
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_canvas.py", line 411, in clear_saturation
    self.draw()
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\backends\backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\cbook\deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\axes\_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\image.py", line 643, in draw
    im, l, b, trans = self.make_image(
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\image.py", line 928, in make_image
    return self._make_image(self._A, bbox, transformed_bbox, clip,
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\image.py", line 547, in _make_image
    output = self.norm(resampled_masked)
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\colors.py", line 1192, in __call__
    self._check_vmin_vmax()
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\matplotlib\colors.py", line 1181, in _check_vmin_vmax
    raise ValueError("minvalue must be positive")
ValueError: minvalue must be positive
```

**Comment by joelvbernier** [comment]
Superceded by https://github.com/HEXRD/hexrdgui/issues/1120.
