### ISSUE TITLE
Rietveld option not running in the GUI

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#951]
The first time I switch option from LeBail to Rietveld, the parameter list is correct. However, switching to Rietveld doesn't update the parameter list. When I hit run, I end up with the following errors

```/Users/saransh1/anaconda3/envs/hgui/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/saransh1/anaconda3/envs/hgui/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/Users/saransh1/hexrdgui/hexrd/ui/calibration/wppf_options_dialog.py", line 243, in update_params
    params = self.generate_params()
  File "/Users/saransh1/hexrdgui/hexrd/ui/calibration/wppf_options_dialog.py", line 236, in generate_params
    return generate_params(**kwargs)
  File "/Users/saransh1/hexrdgui/hexrd/ui/calibration/wppf_options_dialog.py", line 684, in generate_params
    return func_dict[method](materials, peak_shape)
  File "/Users/saransh1/hexrd/hexrd/wppf/wppfsupport.py", line 413, in _generate_default_parameters_Rietveld
    _add_atominfo_to_params(params, m)
  File "/Users/saransh1/hexrd/hexrd/wppf/wppfsupport.py", line 175, in _add_atominfo_to_params
    atom_type = mat.atom_type
AttributeError: 'Material' object has no attribute 'atom_type'
Traceback (most recent call last):
  File "/Users/saransh1/hexrdgui/hexrd/ui/calibration/wppf_runner.py", line 48, in run_wppf
    self.wppf_object = dialog.wppf_object
  File "/Users/saransh1/hexrdgui/hexrd/ui/calibration/wppf_options_dialog.py", line 605, in wppf_object
    self._wppf_object = self.create_wppf_object()
  File "/Users/saransh1/hexrdgui/hexrd/ui/calibration/wppf_options_dialog.py", line 622, in create_wppf_object
    return class_type(**self.wppf_object_kwargs)
  File "/Users/saransh1/hexrd/hexrd/wppf/WPPF.py", line 1503, in __init__
    self.PolarizationFactor()
  File "/Users/saransh1/hexrd/hexrd/wppf/WPPF.py", line 1699, in PolarizationFactor
    Ph = self.Ph
  File "/Users/saransh1/hexrd/hexrd/wppf/WPPF.py", line 2603, in Ph
    return self._Ph
AttributeError: 'Rietveld' object has no attribute '_Ph'
Traceback (most recent call last):
```
My best guess is its likely coming from some initialization error. It seemed to work for a different dataset when I last tested it.

**Comment by saransh13** [comment]
Never mind figured it out. There was a problem in the material class. Should be fixed now.
